In [2]:
import pandas as pd
import json

In [33]:
with open("rules.json", "r", encoding="utf-8") as f:
    rules_data = json.load(f)

df = pd.DataFrame(rules_data)
df.head(5)

,core-id,cdisc_rule_id,standard,executability,status,standard_source,core_id_is_null,core_id_startswith_CORE,in_cache,rule_in_mltple_standards,sharepoint_source,negative_folder_path,negative_regressions,positive_folder_path,positive_regressions
0,CDISC.ADAMIG.111,111,ADaMIG,Fully Executable,Draft,ADAMIG,False,False,False,[],NaN,NaN,NaN,NaN,NaN
1,CDISC.ADAMIG.252,252,ADaMIG,Fully Executable,Draft,ADAMIG,False,False,False,[],NaN,NaN,NaN,NaN,NaN
2,CDISC.ADAMIG.AD0019,19,ADaMIG,Fully Executable,Draft,ADAMIG,False,False,False,[],NaN,NaN,NaN,NaN,NaN
3,CDISC.ADAMIG.AD0020,20,ADaMIG,Fully Executable,Draft,ADAMIG,False,False,False,[],NaN,NaN,NaN,NaN,NaN
4,CDISC.ADAMIG.AD0021,21,ADaMIG,Fully Executable,Draft,ADAMIG,False,False,False,[],NaN,NaN,NaN,NaN,NaN

In [74]:

test_data = df.explode("positive_regressions")
test_data = test_data[test_data["positive_regressions"].notnull()]
test_data['positive_regressions'] = test_data['positive_regressions'].apply(lambda v: next(val['engine_regression'] for val in v.values()))
test_data = test_data[test_data['positive_regressions'].notnull()]
test_data.head(5)

,core-id,cdisc_rule_id,standard,executability,status,standard_source,core_id_is_null,core_id_startswith_CORE,in_cache,rule_in_mltple_standards,sharepoint_source,negative_folder_path,negative_regressions,positive_folder_path,positive_regressions
233,CORE-000001,"CG0176, TIG0405","SDTMIG, TIG",Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0176/negative,[{'SDTMIG/CG0176/negative/01': {'test_case_xsl...,SDTMIG/CG0176/positive,"{'define_xml_present': False, 'datasets_conver..."
234,CORE-000002,CG0208,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0208/negative,[{'SDTMIG/CG0208/negative/01': {'test_case_xsl...,SDTMIG/CG0208/positive,"{'define_xml_present': False, 'datasets_conver..."
236,CORE-000004,"CG0101, TIG0366","SDTMIG, TIG",Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0101/negative,[{'SDTMIG/CG0101/negative/01': {'test_case_xsl...,SDTMIG/CG0101/positive,"{'define_xml_present': False, 'datasets_conver..."
237,CORE-000005,CG0102,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0102/negative,[{'SDTMIG/CG0102/negative/01': {'test_case_xsl...,SDTMIG/CG0102/positive,"{'define_xml_present': False, 'datasets_conver..."
238,CORE-000006,"CG0131, TIG0381","SDTMIG, TIG",Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0131/negative,[{'SDTMIG/CG0131/negative/01': {'test_case_xsl...,SDTMIG/CG0131/positive,"{'define_xml_present': False, 'datasets_conver..."

In [75]:
test_data['comparison'] = test_data["positive_regressions"].map(lambda v: v.get('old_vs_sql', None))
test_data = test_data[test_data['comparison'].notnull()]
test_data[[c.get("equal", None) is None for c in test_data['comparison']]]
test_data[[c.get("number_of_errors_mismatch", False) for c in test_data['comparison']]]

,core-id,cdisc_rule_id,standard,executability,status,standard_source,core_id_is_null,core_id_startswith_CORE,in_cache,rule_in_mltple_standards,sharepoint_source,negative_folder_path,negative_regressions,positive_folder_path,positive_regressions,comparison
322,CORE-000093,"CG0114, TIG0377","SDTMIG, TIG",Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0114/negative,[{'SDTMIG/CG0114/negative/01': {'test_case_xsl...,SDTMIG/CG0114/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
411,CORE-000182,"CG0310, SEND2, TIG0485, TIG0128","SDTMIG, SENDIG, SENDIG-DART, SENDIG-GENETOX, TIG",Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0310/negative,[{'SDTMIG/CG0310/negative/01': {'test_case_xsl...,SDTMIG/CG0310/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
411,CORE-000182,"CG0310, SEND2, TIG0485, TIG0128","SDTMIG, SENDIG, SENDIG-DART, SENDIG-GENETOX, TIG",Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0310/negative,[{'SDTMIG/CG0310/negative/01': {'test_case_xsl...,SDTMIG/CG0310/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
507,CORE-000297,CG0501,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0501/negative,[{'SDTMIG/CG0501/negative/01': {'test_case_xsl...,SDTMIG/CG0501/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
507,CORE-000297,CG0501,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0501/negative,[{'SDTMIG/CG0501/negative/01': {'test_case_xsl...,SDTMIG/CG0501/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
507,CORE-000297,CG0501,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0501/negative,[{'SDTMIG/CG0501/negative/01': {'test_case_xsl...,SDTMIG/CG0501/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
507,CORE-000297,CG0501,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0501/negative,[{'SDTMIG/CG0501/negative/01': {'test_case_xsl...,SDTMIG/CG0501/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
507,CORE-000297,CG0501,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0501/negative,[{'SDTMIG/CG0501/negative/01': {'test_case_xsl...,SDTMIG/CG0501/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
527,CORE-000335,CG0280,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0280/negative,[{'SDTMIG/CG0280/negative/01': {'test_case_xsl...,SDTMIG/CG0280/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
548,CORE-000362,CG0037,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0037/negative,[{'SDTMIG/CG0037/negative/01': {'test_case_xsl...,SDTMIG/CG0037/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
573,CORE-000468,CG0276,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0276/negative,[{'SDTMIG/CG0276/negative/01': {'test_case_xsl...,SDTMIG/CG0276/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
574,CORE-000469,CG0277,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0277/negative,[{'SDTMIG/CG0277/negative/01': {'test_case_xsl...,SDTMIG/CG0277/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
575,CORE-000470,CG0278,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0278/negative,[{'SDTMIG/CG0278/negative/01': {'test_case_xsl...,SDTMIG/CG0278/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
576,CORE-000473,CG0272,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0272/negative,[{'SDTMIG/CG0272/negative/01': {'test_case_xsl...,SDTMIG/CG0272/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
576,CORE-000473,CG0272,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0272/negative,[{'SDTMIG/CG0272/negative/01': {'test_case_xsl...,SDTMIG/CG0272/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
579,CORE-000497,CG0279,SDTMIG,Partially Executable - Possible Overreporting,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0279/negative,[{'SDTMIG/CG0279/negative/01': {'test_case_xsl...,SDTMIG/CG0279/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
604,CORE-000544,CG0028,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0028/negative,[{'SDTMIG/CG0028/negative/01': {'test_case_xsl...,SDTMIG/CG0028/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
609,CORE-000562,CG0273,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0273/negative,[{'SDTMIG/CG0273/negative/01': {'test_case_xsl...,SDTMIG/CG0273/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
609,CORE-000562,CG0273,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0273/negative,[{'SDTMIG/CG0273/negative/01': {'test_case_xsl...,SDTMIG/CG0273/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
617,CORE-000581,"CG0368, TIG0532, TRC1736a, TRC1736c","SDTMIG, TIG, SENDIG, SENDIG-GENETOX, SENDIG-DA...",Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0368/negative,[{'SDTMIG/CG0368/negative/01': {'test_case_xsl...,SDTMIG/CG0368/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
623,CORE-000597,"CG0043, TIG0322","SDTMIG, TIG",Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0043/negative,[{'SDTMIG/CG0043/negative/01': {'test_case_xsl...,SDTMIG/CG0043/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
670,CORE-000736,FB1116,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],FDA Business Rules,FDA Business Rules/FB1116/negative,[{'FDA Business Rules/FB1116/negative/01': {'t...,FDA Business Rules/FB1116/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
673,CORE-000739,CG0407,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0407/negative,[{'SDTMIG/CG0407/negative/01': {'test_case_xsl...,SDTMIG/CG0407/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
676,CORE-000742,FB1110,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],FDA Business Rules,FDA Business Rules/FB1110/negative,[{'FDA Business Rules/FB1110/negative/01': {'t...,FDA Business Rules/FB1110/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
693,CORE-000777,CG0502,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0502/negative,[{'SDTMIG/CG0502/negative/01': {'test_case_xsl...,SDTMIG/CG0502/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
693,CORE-000777,CG0502,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0502/negative,[{'SDTMIG/CG0502/negative/01': {'test_case_xsl...,SDTMIG/CG0502/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
693,CORE-000777,CG0502,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0502/negative,[{'SDTMIG/CG0502/negative/01': {'test_case_xsl...,SDTMIG/CG0502/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
693,CORE-000777,CG0502,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0502/negative,[{'SDTMIG/CG0502/negative/01': {'test_case_xsl...,SDTMIG/CG0502/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
693,CORE-000777,CG0502,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0502/negative,[{'SDTMIG/CG0502/negative/01': {'test_case_xsl...,SDTMIG/CG0502/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."